spring:
  #druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: oracle.jdbc.OracleDriver
      #url: jdbc:oracle:thin:@192.168.3.18:1521:orcl
      url: jdbc:oracle:thin:@139.198.15.74:33066:xe
      username: hbdev
      password: dooffe
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        formal_sql: true
  profiles:
    active: db, wx, gateway, ts, common
  cache:
    type: redis
    cache-names: hbwx
    redis:
      time-to-live: 30000
      cache-null-values: false
  redis:
    # 单机配置
    host: 127.0.0.1
    port: 6379
    # 哨兵模式
    #sentinel:
      #master: mymaster
      #nodes: 192.168.1.83:26379,192.168.1.78:26379,192.168.1.79:26379
      #nodes: 192.168.10.21:26379,192.168.10.21:26380,192.168.10.21:26381
    #database: 0
    #database: 1
    #password: ENC(/rBHb1sQ2onBlD+W5tqi8A==)
    #password: Dooffe123
    timeout: 6000
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  thymeleaf:
    suffix: .html
  #可以访问静态资源
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  session:
    store-type: redis
    timeout:
    redis:
      flush-mode: on-save
      namespace: spring:session
  rabbitmq:
    addresses: 192.168.1.206:5672,192.168.1.233:225672,192.168.1.219:225672
    username: admin
    password: admin


redis:
  host: localhost
  port: 6379
  maxTotal: 3
  maxIdle: 5
  testonBorrow: true
  timeout: 10
  pool:
    max-active: 1024
    max-idle: 10
    min-idle: 10
    max-wait: 10000
server:
  port: 1001



